POST http://localhost:5000/index
Content-Type: application/json

{
    "title": "Item 2",
    "description": "teste"
}

###

GET http://localhost:5000/index

###

PUT http://localhost:5000/index/1
Content-Type: application/json

{
    "title": "Item 3",
    "description": "testado"
}

###

DELETE http://localhost:5000/index/1


###